version: "3.4"

services:
  replicator:
    build: ./build
    image: ipfs-replicator.dnp.dappnode.eth:0.1.0
    container_name: replicator
    restart: always
    volumes:
      - pin-data:/usr/src/app/data
    environment:
      - IPFS_API_URL=http://ipfs:5001
      - REGISTRY_CSV=dnp.dappnode.eth
      - IPFS_CLUSTER_HOST=127.0.0.1
      - IPFS_CLUSTER_PORT=9094
    ports:
      - 8080:8080
    logging:
      options:
        max-size: 10m
        max-file: "3"

volumes:
  pin-data: {}
